# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rosgui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1383, 898)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 150, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.static_split = QtWidgets.QPushButton(self.centralwidget)
        self.static_split.setGeometry(QtCore.QRect(1060, 60, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.static_split.setFont(font)
        self.static_split.setObjectName("static_split")
        self.upload_button = QtWidgets.QPushButton(self.centralwidget)
        self.upload_button.setGeometry(QtCore.QRect(380, 60, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.upload_button.setFont(font)
        self.upload_button.setObjectName("upload_button")
        self.subscribe_label = QtWidgets.QLabel(self.centralwidget)
        self.subscribe_label.setGeometry(QtCore.QRect(530, 481, 321, 31))
        self.subscribe_label.setText("")
        self.subscribe_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subscribe_label.setObjectName("subscribe_label")
        self.size_label = QtWidgets.QLabel(self.centralwidget)
        self.size_label.setGeometry(QtCore.QRect(528, 541, 321, 31))
        self.size_label.setText("")
        self.size_label.setAlignment(QtCore.Qt.AlignCenter)
        self.size_label.setObjectName("size_label")
        self.upload_label = QtWidgets.QLabel(self.centralwidget)
        self.upload_label.setGeometry(QtCore.QRect(390, 710, 601, 31))
        self.upload_label.setText("")
        self.upload_label.setAlignment(QtCore.Qt.AlignCenter)
        self.upload_label.setObjectName("upload_label")
        self.browse_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_button.setGeometry(QtCore.QRect(40, 60, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.browse_button.setFont(font)
        self.browse_button.setObjectName("browse_button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(720, 150, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(710, 210, 641, 231))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bag_info_list = QtWidgets.QListWidget(self.frame)
        self.bag_info_list.setGeometry(QtCore.QRect(0, 0, 641, 231))
        self.bag_info_list.setObjectName("bag_info_list")
        self.progress_bar_upload = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar_upload.setGeometry(QtCore.QRect(488, 711, 401, 31))
        self.progress_bar_upload.setProperty("value", 24)
        self.progress_bar_upload.setObjectName("progress_bar_upload")
        self.progress_label = QtWidgets.QLabel(self.centralwidget)
        self.progress_label.setGeometry(QtCore.QRect(388, 673, 601, 31))
        self.progress_label.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_label.setObjectName("progress_label")
        self.cancel_upload_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_upload_button.setGeometry(QtCore.QRect(900, 711, 111, 31))
        self.cancel_upload_button.setObjectName("cancel_upload_button")
        self.realtime_split = QtWidgets.QPushButton(self.centralwidget)
        self.realtime_split.setGeometry(QtCore.QRect(720, 60, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.realtime_split.setFont(font)
        self.realtime_split.setObjectName("realtime_split")
        self.stop_recording_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_recording_button.setGeometry(QtCore.QRect(900, 481, 121, 31))
        self.stop_recording_button.setObjectName("stop_recording_button")
        self.topic_list = QtWidgets.QListWidget(self.centralwidget)
        self.topic_list.setGeometry(QtCore.QRect(30, 210, 651, 231))
        self.topic_list.setObjectName("topic_list")
        self.onedrive_size = QtWidgets.QLabel(self.centralwidget)
        self.onedrive_size.setGeometry(QtCore.QRect(350, 770, 681, 71))
        self.onedrive_size.setText("")
        self.onedrive_size.setAlignment(QtCore.Qt.AlignCenter)
        self.onedrive_size.setObjectName("onedrive_size")
        self.folder_size = QtWidgets.QLabel(self.centralwidget)
        self.folder_size.setGeometry(QtCore.QRect(350, 600, 681, 61))
        self.folder_size.setText("")
        self.folder_size.setAlignment(QtCore.Qt.AlignCenter)
        self.folder_size.setObjectName("folder_size")
        self.connection_label = QtWidgets.QLabel(self.centralwidget)
        self.connection_label.setGeometry(QtCore.QRect(50, 11, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.connection_label.setFont(font)
        self.connection_label.setText("")
        self.connection_label.setObjectName("connection_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1383, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Select Topics"))
        self.static_split.setText(_translate("MainWindow", "Static Split"))
        self.upload_button.setText(_translate("MainWindow", "Upload to OneDrive"))
        self.browse_button.setText(_translate("MainWindow", "Browse Bag"))
        self.label_2.setText(_translate("MainWindow", "Bag Info"))
        self.progress_label.setText(_translate("MainWindow", "Upload Progress"))
        self.cancel_upload_button.setText(_translate("MainWindow", "Cancel Upload"))
        self.realtime_split.setText(_translate("MainWindow", "Real Time Split"))
        self.stop_recording_button.setText(_translate("MainWindow", "Stop Recording"))
